# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:20
from __future__ import unicode_literals

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20170126_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(default=customer.models.generate_contract_id, max_length=20, primary_key=True, serialize=False)),
                ('total_contract_amount', models.IntegerField(default=0)),
                ('tax_percentage', models.IntegerField(default=0)),
                ('net_contract_amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('contract_type', models.CharField(choices=[('amc', 'AMC'), ('s', 'Single'), ('st', 'Short Term')], max_length=5)),
                ('description', models.TextField()),
                ('is_tax_applicable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contract_added_by', to='userprofile.UserProfile')),
                ('contract_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=customer.models.generate_customer_id, max_length=20, primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('res', 'Residential'), ('cmcl', 'Commercial')], db_index=True, max_length=5)),
                ('company_name', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('salutation', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms')], max_length=4)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.TextField()),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('hotel', 'Hotels & Resorts'), ('it', 'IT Companies'), ('co', 'Corporate Offices'), ('fpu', 'Food Processing Units'), ('go', 'Government Offices')], max_length=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_added_by', to='userprofile.UserProfile')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_edited_by', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.CharField(default=customer.models.generate_enquiry_id, max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('f', 'Followup'), ('c', 'Confirmed'), ('n', 'Not Interested'), ('i', 'Inspection')], max_length=5)),
                ('comments', models.TextField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_added_by', to='userprofile.UserProfile')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_edited_by', to='userprofile.UserProfile')),
                ('reminder_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('f', 'Followup'), ('c', 'Confirmed'), ('n', 'Not Interested'), ('i', 'Inspection')], max_length=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnquiryLog_added_by', to='userprofile.UserProfile')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnquiryLog_edited_by', to='userprofile.UserProfile')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='service_required',
            field=models.ManyToManyField(to='customer.EnquiryService'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contract_edited_by', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Enquiry'),
        ),
    ]
