# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170202_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirylog',
            name='date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirylog',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
