# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170207_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='created_date',
            new_name='enquiry_date',
        ),
    ]
