# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20170211_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='no_of_services',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
