# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20170212_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('100', '100% Advance')], max_length=20, null=True),
        ),
    ]
