# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170212_0632'),
        ('customer', '0011_auto_20170212_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('bill_amount', models.FloatField(blank=True, null=True)),
                ('recieved_amount', models.FloatField(blank=True, null=True)),
                ('tds_deducted', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('balance_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('b', 'Billed')], default='p', max_length=3)),
                ('collection_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('deposited_to', models.CharField(choices=[('iob', 'IOB-A29')], default='iob', max_length=20)),
                ('deposited_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContractInvoice_added_by', to='userprofile.UserProfile')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContractInvoice_edited_by', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContractFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('poor', 'POor')], max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerContractFeedback_added_by', to='userprofile.UserProfile')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerContractFeedback_edited_by', to='userprofile.UserProfile')),
            ],
        ),
    ]
